spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventorydb
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: admin

server:
  port: 4000

jwt:
  secret: mySecretKey
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG